# Origin: This point is taken as the base or reference for all other measurements.
# It is at the center of the front axle, which is a standard reference in automotive
# contexts for measuring any forward or backward distance from the front of the vehicle.
origin: 'center front axle'  

# Reference Point: Measured as an offset from the origin. In this case, y = 0.55 implies
# that it is 0.55 meters forward of the front axle, and x = 0 suggests it is directly in
# line laterally with the front axle.
reference_point_meters:  
  x: 0  # Lateral offset (aligned with the front axle)
  y: 0.55  # Longitudinal offset (forward from the axle)

# Rectangle Width: The width of 0.9 meters is used as a calibration tool for converting
# measurements from pixels to meters. This calibration is essential for precise measurements
# in image processing where the reference point lies at the center of the bottom side of
# the rectangle, ensuring accurate spatial relationships in the image.
rectangle_width_meters: 0.9  # Calibration width in meters, used for pixel to meter conversion

# Conversion factor from pixels to meters
pix2meters: 0.007500000000000001
# Conversion factor from meters to pixels
meters2pix: 133.33333333333331
# Pixel y-coordinate of the reference point. Fliped image coordinate system
yref_px: 40
# Pixel x-coordinate of the reference point. Center of the rectangle.
xref_px: 320

homography: '[[-0.15289882979760036, -1.7137371794936938, 357.4923001054863], [-0.024832391444830428,
  -2.2686259935184356, 471.84484521995444], [-7.760122326509508e-05, -0.0054531971217714635,
  1.0]]'

image_width: 640
image_height: 360

